job('MavenProject-DSL') {
    description("First Maven job generated by DSL on ${new Date()}, this project is a Maven-project hosted on github")
    scm {
        git("https://github.com/souravkar21/mvnwebapp.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean install')
    }
    publishers {
        //archieve the war file generated
        archieveArtifacts '**/*.war'
    }
}