job('MavenProject-DSL') {
    description("First Maven job generated by DSL on ${new Date()}")
    scm {
        git("https://github.com/souravkar21/mvnwebapp.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package')
    }
    publishers {
        //archieve the war file generated
        archieveArtifacts '**/*.war'
    }
}