job('MavenProject') {
    description("First Maven job generated by DSL on ${new Date()}")
    scm {
        git("git@github.com:souravkar21/mvnwebapp.git", master)
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package')
    }
    publishers {
        //archieve the war file generated
        archieveArtifacts '**/*.war'
    }
}